name = "simple-a"
license = "MIT"
licenselink = "https://github.com/AlexFinn/simple-a/blob/master/LICENSE.md"
description = "Minimalistic Hugo theme"
min_version = 0.57

tags = ["AlexFinn", ]
features = ["blog", ]

[author]
    name = "AlexFinn"
    homepage = "http://ru.alxschwarz.com/"
    source_repo = "https://github.com/AlexFinn/simple-a"
